version: "3.8"

services:
  api:
    build: .
    container_name: api

    ports:
      - "5050:5050"

    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres?sslmode=disable

    depends_on:
      - database

  database:
    build: ./database
    container_name: database
